import { type NextPage } from "next";
import Head from "next/head";

const SinglePostPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Post</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div>Post View</div>
      </main>
    </>
  );
};

import { createServerSideHelpers } from "@trpc/react-query/server";
import { createContext } from "server/context";
import { appRouter } from "~/server/api/root";
import { prisma } from "~/server/db";

export const getStaticProps = async (context) => {
const ssg = createServerSideHelpers({
  router: appRouter,
  ctx: { prisma},
  transformer: superjson, // optional - adds superjson serialization
});
}

export default SinglePostPage;
